server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    public-prefix-path: ${POLL_SERVICE_PUBLIC_URL_SERVICE:/api/poll-service}
    private-prefix-path: ${POLL_SERVICE_PRIVATE_URL_SERVICE:/poll-service}
  datasource:
    url: ${POLL_SERVICE_DB_JDBC_URL:jdbc:postgresql://localhost:5432/poll_service?currentSchema=poll_service&user=postgres&password=postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true
        order_inserts: true
    open_in_view: true
  liquibase:
    enabled: ${POLL_SERVICE_LIQUIBASE_ENABLED:false}
    change-log: classpath:db/changelog/master.xml

info:
  application:
    version: '@project.version@'

logging:
  patter:
    console: "${LOG_CONSOLE_PATTERN:%d{yyyy-MM-dd HH:mm:ss.SSS} %+5level --- [%+15.15thread] %-40.40logger{36} : %msg%n}"
  level:
    ROOT: INFO
    org.example: ${POLL_SERVICE_LOG_LEVEL:INFO}
    org.springframework: ${POLL_SERVICE_LOG_LEVEL_SPRING:INFO}
    org.hibernate.sql: ${POLL_SERVICE_LOG_LEVEL_HIBERNATE_SQL:INFO}