server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: poll-service
    public-prefix-path: ${POLL_SERVICE_PUBLIC_URL_PREFIX:/api/poll}
    private-prefix-path: ${POLL_SERVICE_PRIVATE_URL_PREFIX:/poll}
  datasource:
    url: ${POLL_SERVICE_DB_JDBC_URL:jdbc:postgresql://localhost:5432/poll_service?currentSchema=poll_service&user=postgres&password=postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maxLifetime: ${SPRING_DATASOURCE_HIKARI_MAXLIFETIME:1800000}
  jpa:
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
    open-in-view: false
  liquibase:
    enabled: ${POLL_SERVICE_LIQUIBASE_ENABLED:false}
    change-log: classpath:db/changelog/master.xml

management:
  endpoint:
    env:
      keys-to-sanitize:
        - spring.datasource.url
        - POLL_SERVICE_DB_JDBC_URL
      show-values: ALWAYS
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, env
      path-mapping:
        info: ${spring.application.public-prefix-path}/info
        health: /health
        env: ${spring.application.private-prefix-path}/env
      base-path: # сбрасывает дефолтный маппинг актуатора

info:
  application:
    version: '@project.version@'

logging:
  pattern:
    console: "${LOG_CONSOLE_PATTERN:%d{yyyy-MM-dd HH:mm:ss.SSS} %+5level --- [%+15.15thread] %-40.40logger{36} : %msg%n}"
  level:
    ROOT: INFO
    ru.golbi: ${POLL_SERVICE_LOG_LEVEL:INFO}
    org.springframework: ${POLL_SERVICE_LOG_LEVEL_SPRING:INFO}

springdoc:
  packagesToScan: ru.golbi.api.controller
  api-docs:
    path: ${spring.application.private-prefix-path}/swagger/v3/api-docs
  swagger-ui:
    path: ${spring.application.private-prefix-path}/swagger-ui